apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: commerce-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce-api
  template:
    metadata:
      labels:
        app: commerce-api
    spec:
      containers:
        - name: api
          image: pf-commerce-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8099
              name: http
          env:
            - name: COMMERCE_HTTP_PORT
              value: "8099"
            - name: COMMERCE_DEV_AUTH
              value: "true"
            - name: COMMERCE_CORS_ORIGIN
              value: http://commerce.localhost
            - name: COMMERCE_DATABASE_URL
              value: postgres://commerce_gateway:dev-commerce-gateway@postgres.platform.svc.cluster.local:5432/commerce_gateway?sslmode=disable
            - name: COMMERCE_CATALOG_URL
              value: http://catalog.p06.svc.cluster.local:8101
            - name: COMMERCE_INVENTORY_URL
              value: http://inventory.p06.svc.cluster.local:8102
            - name: COMMERCE_ORDER_URL
              value: http://order.p06.svc.cluster.local:8103
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.platform.svc.cluster.local:4318
            - name: OTEL_SERVICE_NAME
              value: commerce-gateway
          readinessProbe:
            httpGet:
              path: /ready
              port: 8099
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8099
            initialDelaySeconds: 30
            periodSeconds: 10
