apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: commerce-catalog
spec:
  selector:
    app: commerce-catalog
  ports:
    - name: http
      port: 8101
      targetPort: 8101
